; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; https://docs.platformio.org/page/projectconf.html


; ================================================================
; Gemeinsame Einstellungen
; ================================================================

[common]

platform = espressif32
framework = arduino

monitor_filters =
    esp32_exception_decoder
    direct

monitor_speed = 115200
upload_speed = 921600

test_framework = unity

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D CONFIG_ARDUHAL_LOG_COLORS=1
    -D BOARD_HAS_PSRAM
    -D AUDIOSTREAM_ENABLE_DYNAMIC_LIFETIME

build_src_flags =
    -Wall
    -Wextra
    -O2


; ================================================================
; ESP32 Audio Kit
; ================================================================

[env:esp32-audio-kit]

platform = ${common.platform}
framework = ${common.framework}

board = esp32dev

monitor_filters = ${common.monitor_filters}
monitor_speed = ${common.monitor_speed}
upload_speed = ${common.upload_speed}
test_framework = ${common.test_framework}

board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_qspi

build_flags =
    ${common.build_flags}
    -mfix-esp32-psram-cache-issue

build_src_flags =
    ${common.build_src_flags}
    -D AUDIO_CODEC_ES8388
    -D PIN_I2C_SCL=32
    -D PIN_I2C_SDA=33
    -D PIN_AMPLIFIER=21
    -D PIN_AMPLIFIER_ACTIVE=HIGH

    -D PIN_I2S_BLCK=27
    -D PIN_I2S_WS=25
    -D PIN_I2S_DOUT=26
    -D PIN_I2S_MLCK=0


; ================================================================
; Freenove ESP32-S3 Display 2.8"
; ================================================================

[env:freenove_esp32_s3_display]

platform = ${common.platform}
framework = ${common.framework}

board = esp32-s3-devkitc-1

monitor_filters = ${common.monitor_filters}
monitor_speed = ${common.monitor_speed}
upload_speed = ${common.upload_speed}

test_framework = ${common.test_framework}

; ESP32-S3 / N16R8
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L

board_build.flash_mode = dio
board_build.psram_type = opi
board_build.arduino.memory_type = dio_opi

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

board_build.partitions = default_16MB.csv

build_flags =
    ${common.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

build_src_flags =
    ${common.build_src_flags}
    -D AUDIO_CODEC_ES8311
    -D PIN_I2C_SCL=15
    -D PIN_I2C_SDA=16

    -D PIN_AMPLIFIER=1
    -D PIN_AMPLIFIER_ACTIVE=LOW

    -D PIN_I2S_BLCK=5
    -D PIN_I2S_WS=7
    -D PIN_I2S_DOUT=8
    -D PIN_I2S_MLCK=4

    -D PIN_SD_CS=10
    -D PIN_SPI_MOSI=11
    -D PIN_SPI_MISO=13
    -D PIN_SPI_SCK=12
