; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-audio-kit]
platform = espressif32
board = esp32dev
framework = arduino

; PSRAM Unterstützung für ESP32-WROVER / Audio-Kit aktivieren
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_qspi ; Passt für Standard ESP32-WROVER

; Test-Framework (Unity ist bereits integriert, lib_deps nicht zwingend nötig)
test_framework = unity

; Globale Flags für das gesamte Projekt
build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D BOARD_HAS_PSRAM
    ;-D AUDIO_SAMPLE_RATE_EXACT=48000.0f
    -D AUDIOSTREAM_ENABLE_DYNAMIC_LIFETIME
    ; Activate on ESP32 Rev.1 only:
    -mfix-esp32-psram-cache-issue

; Spezifische Flags nur für den Quellcode in src/
build_src_flags =
    -Wall
    -Wextra
    -O2
